### ISSUE TITLE
Poppins 500 not downloading

### ISSUE THREAD

**Issue by bloomlive** [nuxt-community/google-fonts-module#101]
Nuxt 3 RC 6 + google-fonts 3.0.0-0 

`    googleFonts: {
        families: {
            Poppins: {
                wght: [300, 400, 500, 600, 700],
            },
        },
        display: 'swap',
        prefetch: true,
        preconnect: false,
        download: true,
        base64: false,
        useStylesheet: false,
    },`

Poppins is not downloaded in specified weights, missing 500.

**Comment by asmeeee** [comment]
Same for `Montserrat`, it ignores all weights and injects only 400.

**Comment by fnavarijo** [comment]
I'm having the same issue with `Roboto`. Is injecting only `400`.

**Comment by fnavarijo** [comment]
I think I've found what is happening.
The library depends on `google-fonts-helper`. This helps with the download of the fonts.  When the [execute](https://github.com/nuxt-community/google-fonts-module/blob/36e89d26058d55a7d64e57152a7f30d1360bffb2/src/module.ts#L93) method is called, it verifies that the `.cache/nuxt-google-fonts` exists. In case that it does, it returns
``` js
  // google-fonts-helpers
  if (!overwriting && fsExtra.pathExistsSync(cssPath)) {
      return;
    }
```

I was able to update my fonts adding the `overwriting` flag
``` js
// nuxt.config.js

export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@nuxtjs/google-fonts'],
  googleFonts: {
    families: {
      Roboto: [100, 300],
      Lato: [100, 300, 500]
    },
    overwriting: true // this flag
  }
})
```

The downside, is that everytime your server restarts, will fetch the fonts again.

**Comment by asmeeee** [comment]
> I think I've found what is happening. The library depends on `google-fonts-helper`. This helps with the download of the fonts. When the [execute](https://github.com/nuxt-community/google-fonts-module/blob/36e89d26058d55a7d64e57152a7f30d1360bffb2/src/module.ts#L93) method is called, it verifies that the `.cache/nuxt-google-fonts` exists. In case that it does, it returns ([ref](https://github.com/datalogix/google-fonts-helper/blob/9561a498023389339ebef27e1332e2d091e429c8/src/google-fonts-helper.ts#L124))
> 
> ```js
>   // google-fonts-helpers
>   if (!overwriting && fsExtra.pathExistsSync(cssPath)) {
>       return;
>     }
> ```
> 
> I was able to update my fonts adding the `overwriting` flag
> 
> ```js
> // nuxt.config.js
> 
> export default defineNuxtConfig({
>   modules: ['@nuxtjs/tailwindcss', '@nuxtjs/google-fonts'],
>   googleFonts: {
>     families: {
>       Roboto: [100, 300],
>       Lato: [100, 300, 500]
>     },
>     overwriting: true // this flag
>   }
> })
> ```
> 
> The downside, is that everytime your server restarts, will fetch the fonts again.
> 
> The other quick solution is removing `node_modules/.cache/nuxt-google-fonts` and starting the server again 😄

I decided to just download the variable font locally and use it.

**Comment by bloomlive** [comment]
Yup, it seems to be it.

**Comment by carlosmori** [comment]
> I think I've found what is happening. The library depends on `google-fonts-helper`. This helps with the download of the fonts. When the [execute](https://github.com/nuxt-community/google-fonts-module/blob/36e89d26058d55a7d64e57152a7f30d1360bffb2/src/module.ts#L93) method is called, it verifies that the `.cache/nuxt-google-fonts` exists. In case that it does, it returns ([ref](https://github.com/datalogix/google-fonts-helper/blob/9561a498023389339ebef27e1332e2d091e429c8/src/google-fonts-helper.ts#L124))
> 
> ```js
>   // google-fonts-helpers
>   if (!overwriting && fsExtra.pathExistsSync(cssPath)) {
>       return;
>     }
> ```
> 
> I was able to update my fonts adding the `overwriting` flag
> 
> ```js
> // nuxt.config.js
> 
> export default defineNuxtConfig({
>   modules: ['@nuxtjs/tailwindcss', '@nuxtjs/google-fonts'],
>   googleFonts: {
>     families: {
>       Roboto: [100, 300],
>       Lato: [100, 300, 500]
>     },
>     overwriting: true // this flag
>   }
> })
> ```
> 
> The downside, is that everytime your server restarts, will fetch the fonts again.
> 
> The other quick solution is removing `node_modules/.cache/nuxt-google-fonts` and starting the server again 😄

god bless you

**Comment by ricardogobbosouza** [comment]
- Use the [`overwrite`](https://google-fonts.nuxtjs.org/downloading#overwriting) option 

In next release https://github.com/nuxt-community/google-fonts-module/pull/105  it will be detected automatically

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen

**Comment by kissu** [comment]
Works fine with the latest, thanks Ricardo! 🙏🏻
