### ISSUE TITLE
node_modules/.cache/nuxt-google-fonts needs to be deleted on font-family addition/removal

### ISSUE THREAD

**Issue by Jonny15t** [nuxt-community/google-fonts-module#102]
**The issue:**
When updating the font families in `nuxt.config.ts` after an initial load, the `node_modules/.cache/nuxt-google-fonts` directory doesn't update the `css` or `files` contents to match the settings.

**How to recreate:**
Follow the documentation for installing w/ `nuxt3` and select an initial font-family (i.e. Roboto). Add additional families and/or remove the initial family. Update styling to use new families and restart server. *If initial family removed, previous styling will break. New families will not be included.* Navigate to `node_modules/.cache/nuxt-google-fonts/` and view that `/css` and `/fonts` files only represent the initial settings.

**Work around:**
Delete the `node_modules/.cache/nuxt-google-fonts` directory and restart the `nuxt3` server. The module will populate the cache with the updated settings.

**Supporting information:**
versions
```  
"devDependencies": {
  "nuxt": "3.0.0-rc.9",
},
"dependencies": {
  "@nuxtjs/google-fonts": "^3.0.0-0"
}
```

nuxt.config.ts
```
export default defineNuxtConfig({
  srcDir: "./src",
  modules: ["nuxt-icon", "@nuxtjs/google-fonts"],
  googleFonts: {
    download: true,
    subsets: "latin",
    families: {
      Roboto: [300, 400, 500, 700],
      Ubuntu: [400, 500, 700],
    },
  },
});
```

**Comment by TheMangoTrain** [comment]
I'm experiencing the same thing (Nuxt2).

Updated my nuxt.config.js and saw no change occur. Observed the cache folder with certain files, but not ones I expect. After server re-start and refresh the page in browser, my new font config fully loads.

**Comment by vaban-ru** [comment]
Same thing in Nuxt 3

**Comment by jhull** [comment]
Thank you! Beating my head against the wall on this one - add my name to the list (Nuxt 3 @rc10)

**Comment by melrefaie** [comment]
Same issue

**Comment by ricardogobbosouza** [comment]
Fixed in next release https://github.com/nuxt-community/google-fonts-module/pull/105 

- The overwriting option will be detected automatically

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen
