### ISSUE TITLE
fonts with option `download: true` ignore `display` (always are 'block')

### ISSUE THREAD

**Issue by hartmut-co-uk** [nuxt-community/google-fonts-module#103]
Fonts downloaded always seem to be `font-display: block;` and ignore the `display` option.

    googleFonts: {
        display: 'swap', // 'auto' | 'block' | 'swap' | 'fallback' | 'optional'
        download: true,
        families: {
            Inter: {
                wght: [200, 300, 400, 500, 600, 700],
            },
            Montserrat: {
                wght: [200, 300, 400, 500, 600, 700],
            },
        }
    }

Resulting in following css:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/10864443/193809521-dba52b7b-a798-488f-9485-ea6a5cb0bcfe.png">

Or is there any rationale for enforcing 'block' for downloaded fonts?

**Comment by ricardogobbosouza** [comment]
Hi @hartmut-co-uk 

- Use the [`overwrite`](https://google-fonts.nuxtjs.org/downloading#overwriting) option 

In next release https://github.com/nuxt-community/google-fonts-module/pull/105  it will be detected automatically

**Comment by hartmut-co-uk** [comment]
thx for the reply! 🙇 
I'll wait for this upcoming release, try again and report back / close.

**Comment by hartmut-co-uk** [comment]
@ricardogobbosouza are you planning to release `v3.0.0-1` to npm?

**Comment by ricardogobbosouza** [comment]
Hi @hartmut-co-uk 

Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by hartmut-co-uk** [comment]
Many thanks, I can confirm everything works as expected with `v3.0.0-1`.
Even without specifying `overwriting` option changes are detected and applied. 👍
