### ISSUE TITLE
fonts.css 404

### ISSUE THREAD

**Issue by Daewon25** [nuxt-community/google-fonts-module#104]
Hi there.

GET https://localhost:3000/_nuxt/fonts.css net::ERR_ABORTED 404 (Not Found)

My **nuxt.config.js**

['@nuxtjs/google-fonts', { display: 'swap', download: true, families: { Raleway: ['300', '400', '500', '600', '700'], Roboto: ['300', '400', '500', '700'] } }],

And also where is Raleway 700, 300 & Roboto 500 700?

![image](https://user-images.githubusercontent.com/45786480/194032458-e7abf872-becf-425a-a812-ff65f2be8386.png)

What im doing wrong?

**Comment by ricardogobbosouza** [comment]
Hi @Daewon25 

- Use the [`overwrite`](https://google-fonts.nuxtjs.org/downloading#overwriting) option 

In next release https://github.com/nuxt-community/google-fonts-module/pull/105  it will be detected automatically

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen
