### ISSUE TITLE
Cannot read 'resolveAlias' when using with Nuxt 3

### ISSUE THREAD

**Issue by lightcode22** [nuxt-community/google-fonts-module#107]
I want to add google-fonts to my Nuxt 3 project and follow [the docs](https://google-fonts.nuxtjs.org/setup).

I added a font like this

```
googleFonts: {
    download: true,
    display: 'swap',
    families: {
        Montserrat: {
            wght: [400,500,600],
            ital: [400,500,600]
        },
    }
}
```
But when I try to run the project in dev mode I get an error

**Cannot start nuxt:  Cannot read properties of undefined (reading 'resolveAlias')
 at node_modules\@nuxtjs\google-fonts\dist\module.js:59:44**

and this is what the line looks like

**const outputDir = this.nuxt.resolver.resolveAlias(options.outputDir);**

**Comment by kaarelsirel** [comment]
I have the same problem. Using the pre-release version ^3.0.0-1 seems to be working, but there is still an error:

`Invalid response body while trying to fetch https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZFhiI2B.woff2: aborted`

My config:
```
googleFonts: {
  download: true,
  families: {
    Inter: true,
  },
},
```

**Comment by iamandrewluca** [comment]
For Nuxt 3 you need to install version 3 of this module (prerelease tag)

```shell
npm install --save-dev @nuxtjs/google-fonts@prerelease
```

**Comment by lightcode22** [comment]
could you please put this information somewhere on the module website or github page? It will save someone's time and nerves one day

**Comment by lightcode22** [comment]
Another problem. When requesting 'Noto+Sans+KR' font I get an error
**(https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&family=Noto+Sans%2BKR:wght@300;400;500;700&display=swap)**
The second plus sign is interpreted as %2B so the ething fails.

**Comment by iamandrewluca** [comment]
Unfortunately, I don't have write permission on this repo. If you want you can create a PR that adds that info.

**Comment by codernirdesh** [comment]
Thank you @iamandrewluca for your simple yet great answer for this issue. I was unable to use this package.
You saved me today. ❤️

**Comment by llops** [comment]
Same here! Thank you @iamandrewluca!

**Comment by ThePlastic** [comment]
It isn't solved, still get the error with `"@nuxtjs/google-fonts": "^3.1.3",`
