### ISSUE TITLE
googleFonts does not exist in type 'NuxtConfig'

### ISSUE THREAD

**Issue by narr07** [nuxt-community/google-fonts-module#109]
**package.json**
`"@nuxtjs/google-fonts": "^3.0.0-1",`

**nuxt.config.ts**
  `modules: ["@nuxtjs/google-fonts"],`

  ```
googleFonts: {
      display: 'swap',
      useStylesheet: true,
      inject: true,
      download: true,
      families: {
          'Inter': [300, 400, 500, 600, 700],
          'Open Sans': [300, 400, 500, 600, 700]
      }
```

_error_: Object literal may only specify known properties, and **'googleFonts' does not exist in type 'NuxtConfig**'

**Comment by eli-me** [comment]
I can confirm this problem using the latest version of Nuxt3

**Comment by eli-me** [comment]
After reading the issues a little bit I could find the reason of the problem with Nuxt3, it's because you have to install the pre-release version of this package, see below:


    For Nuxt 3 you need to install version 3 of this module (prerelease tag) and it will work

```shell
npm install --save-dev @nuxtjs/google-fonts@prerelease
```

_Originally posted by @iamandrewluca in https://github.com/nuxt-community/google-fonts-module/issues/107#issuecomment-1300924762_

**Comment by SPH73** [comment]
Even with the prerelease tag, Nuxt can't spin up the dev server.

`Cannot restart nuxt:  Cannot find module '/.../webapp/node_modules/@nuxtjs/google-fonts/dist/module.js'. Please verify that the package.json has a valid "main" entry`

```
nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', "@nuxtjs/google-fonts"],
}
```
```
package.json
"devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.0-1",
}
```

**Comment by dosstx** [comment]
Installing the prerelease version works for me. thanks

**Comment by maximedaraize** [comment]
Installing the prerelease version did the trick.

**Comment by narr07** [comment]
> After reading the issues a little bit I could find the reason of the problem with Nuxt3, it's because you have to install the pre-release version of this package, see below:
> 
> ```
> For Nuxt 3 you need to install version 3 of this module (prerelease tag) and it will work
> ```
> 
> ```shell
> npm install --save-dev @nuxtjs/google-fonts@prerelease
> ```
> 
> _Originally posted by @iamandrewluca in [#107 (comment)](https://github.com/nuxt-community/google-fonts-module/issues/107#issuecomment-1300924762)_

Thanks work use prerelease version

**Comment by MartCube** [comment]
package.json
`"devDependencies": {
		"@nuxtjs/google-fonts": "^3.0.0-1",
		"nuxt": "^3.0.0",
}`
nuxt.config.ts
`modules: ["@nuxtjs/google-fonts"],`

However when I try to type googleFonts in nuxt.config I get the same error
**'googleFonts' does not exist in type 'NuxtConfig'**
What can go wrong ?

**Comment by bst33d** [comment]
I can confirm that using the prerelease version solved the issue for me,
`yarn add @nuxtjs/google-fonts@prerelease`

**Comment by iamandrewluca** [comment]
Works for me

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1881266/225076660-12e3b109-55ce-4790-ae7f-41b3b2061589.png">

**Comment by frankhsiao-ntg** [comment]
I delete `.nuxt/tsconfig.json` manually then `npm i` again. It works for me.

```"@nuxtjs/google-fonts": "^3.0.0"```

**Comment by ThePlastic** [comment]
It isn't solved, still get the error with `"@nuxtjs/google-fonts": "^3.1.3",`

**Comment by subdiox** [comment]
I resolved it with adding `modules: ["@nuxtjs/google-fonts"]` in `nuxt.config.ts`.

**Comment by qiquanlu** [comment]
> I delete `.nuxt/tsconfig.json` manually then `npm i` again. It works for me. You must check if `.nuxt/tsconfig.json` auto generate again.
> 
> `"@nuxtjs/google-fonts": "^3.0.0"`

worked for me, I just delete .nuxt folder to let nuxt re-generate everything
