### ISSUE TITLE
Only some fonts seem to work

### ISSUE THREAD

**Issue by tcober** [nuxt-community/google-fonts-module#112]
I am only able to get specific fonts to work. Pretty much all display fonts seem to fail
'Bangers', 'Lilita One', and 'Lobster' have all failed for me so far

Here is my current config:
```javascript
buildModules: [
    [
      "@nuxtjs/google-fonts",
      {
        googleFonts: {
          download: true,
          prefetch: true,
          families: {
            Bangers: true,
            "PT+Mono": true,
            "PT+Serif": true,
          },
        },
      },
    ],
  ],
  ```
Both of the PT fonts seem to be working. I have tried around a half dozen other fonts though and they will not work.

**Comment by thomas-forster1** [comment]
@tcober 

you might be having the same issue I was having: if you want to change the font family I found that I needed to delete the fonts folder and the css/fonts.css file. after that run `yarn dev or yarn build` Nuxt will now download the correct font files and generate the correct font.css file.

**Comment by ricardogobbosouza** [comment]
Exactly, in previous versions it was necessary to remove the `fonts` folder
As of version [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases) this is no longer necessary
