### ISSUE TITLE
Fonts are downloaded 2 times in public folder

### ISSUE THREAD

**Issue by rmenai** [nuxt-community/google-fonts-module#114]
![image](https://user-images.githubusercontent.com/59766203/206840214-42afe15a-dcce-45e8-8882-e6e0892703f0.png)

So when using this module, I noticed that the fonts are downloaded 2 times. First, in the `.output/public/_nuxt` folder and in the `.output/public/fonts` folder.

Shouldn't it just download it in the `.output/public/fonts` folder?

**Comment by andrzejkupczyk** [comment]
In my case it's even worse. 

```
googleFonts: {
  families: {
    'Roboto+Slab': [300, 400, 500, 600]
  }
}
```

<details>
  <summary>Fonts found in the ".output/public/_nuxt" directory</summary>

```
Roboto_Slab-300-1.31a47841.woff2
Roboto_Slab-300-2.b6872478.woff2
Roboto_Slab-300-4.a772fd70.woff2
Roboto_Slab-300-5.42172087.woff2
Roboto_Slab-300-6.e51239aa.woff2
Roboto_Slab-300-7.9a399391.woff2
```
</details>

<details>
  <summary>Fonts found in the ".output/public/fonts" directory</summary>

```
Roboto_Slab-300-1.woff2
Roboto_Slab-300-2.woff2
Roboto_Slab-300-3.woff2
Roboto_Slab-300-4.woff2
Roboto_Slab-300-5.woff2
Roboto_Slab-300-6.woff2
Roboto_Slab-300-7.woff2
Roboto_Slab-400-8.woff2
Roboto_Slab-400-9.woff2
Roboto_Slab-400-10.woff2
Roboto_Slab-400-11.woff2
Roboto_Slab-400-12.woff2
Roboto_Slab-400-13.woff2
Roboto_Slab-400-14.woff2
Roboto_Slab-500-15.woff2
Roboto_Slab-500-16.woff2
Roboto_Slab-500-17.woff2
Roboto_Slab-500-18.woff2
Roboto_Slab-500-19.woff2
Roboto_Slab-500-20.woff2
Roboto_Slab-500-21.woff2
Roboto_Slab-600-22.woff2
Roboto_Slab-600-23.woff2
Roboto_Slab-600-24.woff2
Roboto_Slab-600-25.woff2
Roboto_Slab-600-26.woff2
Roboto_Slab-600-27.woff2
Roboto_Slab-600-28.woff2
```
</details>

**Comment by PatrikBird** [comment]
did you try this? https://google-fonts.nuxtjs.org/downloading#overwriting
> This option prevents files from being downloaded more than once.

**Comment by ricardogobbosouza** [comment]
Hi @andrzejkupczyk  
If you open the css from https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;500;600&display=swap
It is not necessarily a source for each weight

**Comment by ricardogobbosouza** [comment]
Hi @rmenai 

1. Try deleting the `fonts` folder
2. Update the module to the latest version [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)
3. Run `npm run dev`
