### ISSUE TITLE
Is there a `buildModules` in Nuxt 3?

### ISSUE THREAD

**Issue by k16e** [nuxt-community/google-fonts-module#118]
The documentation advises adding `'@nuxtjs/google-fonts'` to the `buildModules` section of `nuxt.config.js`. But I thought in Nuxt 3 every module went in the `modules` section instead. Or is the documentation yet to be updated to line up with Nuxt 3?

**Comment by aleavikraman** [comment]
There's no buildModule in Nuxt 3 you have to move it in to modules. 

I was able to get this working on nuxt 3 by installing the pre-release `npm install --save-dev @nuxtjs/google-fonts@prerelease`
and adding it to my modules in nuxt.config.ts `modules: ['@nuxtjs/google-fonts'],`

**Comment by k16e-me** [comment]
O, I figured. Thanks for directing, @aleavikraman.
