### ISSUE TITLE
Bad URL in readme in Features > Add Preload

### ISSUE THREAD

**Issue by jjaimealeman** [nuxt-community/google-fonts-module#119]
![screenshot](https://i.imgur.com/G5epzdx.png)

Points here 👎
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Preloading_content

Should point here 👍
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload

**Comment by ricardogobbosouza** [comment]
Thanks @jjaimealeman 
Fixed https://github.com/nuxt-community/google-fonts-module/blob/16e03a8762de5371c4af6b548d2b4015e4a85486/README.md
