### ISSUE TITLE
`text` param with 2 langs

### ISSUE THREAD

**Issue by YosefMets** [nuxt-community/google-fonts-module#120]
How can I use `text` param with 2 langs? I need the first one with all chars and in the second one I need only a few chars. In pure JS I can use 2 `link` tags (one with `text` and second without). But how to do it in this module?

**Comment by damisparks** [comment]
@YosefMets Here are some resources to help you. 
* https://google-fonts.nuxtjs.org/options#text
* https://developers.google.com/fonts/docs/css2#optimizing_your_font_requests

**Comment by YosefMets** [comment]
@damisparks thank you for the links. But my question is how can I use `text` param with **two and more** langs?

**Comment by damisparks** [comment]
> @damisparks thank you for the links. But my question is how can I use `text` param with **two and more** langs?

@YosefMets I understood your question. However, I did some experiments. I do not think the module can do that yet. I am curious to see what the community thinks.

**Comment by ricardogobbosouza** [comment]
Hi @YosefMets 
This is not possible yet

Duplicate #106
