### ISSUE TITLE
Page Speed Insights complaint

### ISSUE THREAD

**Issue by bart** [nuxt-community/google-fonts-module#17]
First of all I want to thank for this nice and handy module. Want to use it for an upcoming project and did some performance testing. Google Page Speed Insights complains with `Eliminate render-blocking resources` when using this module. Looks like `/css2?family=Inter:wght@400;700&display=swap` is blocking loading.

I configured the module like this:
```
googleFonts: {
    families: {
      Inter: [400, 700],
    },
    display: 'swap',
  },
```

Any idea how to solve this? Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @bart 

We must use one of these ways:
https://stackoverflow.com/questions/25230264/how-to-keep-css-from-render-blocking-my-website
https://frontmend.com/asynchronous-google-fonts

**Comment by ricardogobbosouza** [comment]
Hi @bart 
Fixed on v1.1.0

**Comment by bart** [comment]
Awesome, thanks a lot @ricardogobbosouza

**Comment by Beethoven** [comment]
This makes AMP pages invalid. There's a way to make this an option? #24

**Comment by ricardogobbosouza** [comment]
Fixed on [v1.1.3](https://github.com/nuxt-community/google-fonts-module/releases/tag/v1.1.3)

**Comment by fpolica91** [comment]
Question guys, where am I to place this link tags. app.html?

**Comment by Beethoven** [comment]
> Question guys, where am I to place this link tags. app.html?

Just add @nuxtjs/google-fonts to the buildModules section of nuxt.config.js:
https://google-fonts.nuxtjs.org/setup
