### ISSUE TITLE
leverage font-display for best performance

### ISSUE THREAD

**Issue by pi0** [nuxt-community/google-fonts-module#22]
Currently we enable `prefetch`, `preload` and also `preconnect` by default and don't use a `display` strategy! This means even if stop lighhouse complaining about render render blocking resources (https://github.com/nuxt-community/google-fonts-module/commit/84c7f360d6b97eb07a9970a6826b1a7b2a40274b), we do prioritize fonts loading on network requests and we would need inlining a script for async workaround. 

Instead we can leverage (almost) new [`font-display`](https://developers.google.com/web/updates/2016/02/font-display) by default which is smart enough to how to swap/fallback and this behavior should be customizable per-font not globally (depends on usage and impact on design) and we should do `prefetch` for fonts with `block` display.

**Comment by ricardogobbosouza** [comment]
Hi @pi0 
We must set as default `swap` https://github.com/nuxt-community/google-fonts-module#display?

**Comment by pi0** [comment]
@ricardogobbosouza I think that would be the best default (just this is anyway a breaking change to switch from script)

**Comment by ricardogobbosouza** [comment]
@pi0 Itss a breaking change?

**Comment by pi0** [comment]
@ricardogobbosouza I think would be safer to bump major version. Since it changes how webpage progressively loads

**Comment by ricardogobbosouza** [comment]
`font-display` is `swap` by default in [v3](https://github.com/nuxt-community/google-fonts-module/releases/tag/v2.0.0)
