### ISSUE TITLE
Option to not use onload,  vmid: 'google-fonts',  media: 'print', onload and vmid on AMP pages is not supported

### ISSUE THREAD

**Issue by Beethoven** [nuxt-community/google-fonts-module#24]
There's how to disable 
`     vmid: 'google-fonts',
      media: 'print',
      onload: 'this.onload=null;this.removeAttribute(\'media\');'
 `
to use this module on AMP pages

**Comment by ricardogobbosouza** [comment]
Fixed on [v1.1.3](https://github.com/nuxt-community/google-fonts-module/releases/tag/v1.1.3)

**Comment by Beethoven** [comment]
The AMP module removes <script>
So this fix doesn't work 
Need option to use like before:

`    // CSS
    this.options.head.link.push({
      hid: 'google-fonts',
      rel: 'stylesheet',
      href: url,
    })`

**Comment by ricardogobbosouza** [comment]
@Beethoven 
I will add an option for that
