### ISSUE TITLE
crossorigin has invalid value "true"

### ISSUE THREAD

**Issue by borisdayma** [nuxt-community/google-fonts-module#27]
I believe there is an error at [this line](https://github.com/nuxt-community/google-fonts-module/blob/b9c59eafacab263852a7579743081e03536c52d1/lib/module.js#L95).

It raises an error with html-validator:
> error  Attribute "crossorigin" has invalid value "true"  attribute-allowed-values

The rendered element is:
`<link data-n-head="ssr" data-hid="gf-preconnect" rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="true">`

It should be:
`<link data-n-head="ssr" data-hid="gf-preconnect" rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>`

**Comment by andrejsharapov** [comment]
after update `HTML validation errors found for /articles/ error: Attribute "crossorigin" should omit value (attribute-empty-style)`

**Comment by borisdayma** [comment]
According to [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin), the empty string is valid but it's true that html-validator still complains.

An alternative would be to set it to `anonymous` which seems to also be equivalent according to the same page.
