### ISSUE TITLE
Support "text" parameter for font queries

### ISSUE THREAD

**Issue by Hanziness** [nuxt-community/google-fonts-module#36]
Hi!
I've recently noticed that the Google Fonts CSS API v2 has an option to not only specify the `subset` parameter for a font [but also a `text` one](https://developers.google.com/fonts/docs/css2#optimizing_your_font_requests): this is a (URL-enconded) string that contains the characters you want to use from the font and only these will be downloaded. For example, the following URL will result in only the number glyphs being downloaded for the _Source Sans Pro_ font's bold weight, saving a lot of bandwidth by not downloading a full Latin subset of it.
```
https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@700&display=swap&text=1234567890
```

Unfortunately, this module does not seem to support this parameter so I ended up manually importing the font for now, but I would love to see it support this part of the API, too -- especially since I cannot use some of the module's convenient features this way, like automatic prefetching. 

If specified, `text` should be used instead of `subset`, details [here](https://developers.google.com/fonts/docs/css2#optimizing_your_font_requests).

Is there any plan to implement the handling of this parameter?

**Comment by ricardogobbosouza** [comment]
Hi @Hanziness 

I will add this option by the end of the week.
https://github.com/ricardogobbosouza/google-fonts-helper/pull/8

Thanks for reporting 😄

**Comment by Hanziness** [comment]
Awesome, thank you very much! :)
