### ISSUE TITLE
Heads up: Google font CDN not going to be widely available.

### ISSUE THREAD

**Issue by whardier** [nuxt-community/google-fonts-module#38]
https://www.zdnet.com/article/chromes-new-cache-partitioning-system-impacts-google-fonts-performance/

**Comment by ricardogobbosouza** [comment]
Should we enable download by default in the next version!
What do you think @pi0 ?

**Comment by danielroe** [comment]
I think we can close this since https://github.com/nuxt-community/google-fonts-module/pull/87 was merged.

**Comment by ricardogobbosouza** [comment]
`Download `is enable by default
