### ISSUE TITLE
Subsets parameter and download

### ISSUE THREAD

**Issue by galaczi** [nuxt-community/google-fonts-module#40]
Due to the recent changes in Chrome's cache partitioning, I wanted to use the download mode.

My config: 
` 
  buildModules: [
    [
      "@nuxtjs/google-fonts",
      {
        families: {
          Sarabun: {
            wght: [400, 700]
          }
        },
        subsets: ['latin'],
        download: true
      }
    ]
  ]
`

But the result is unexpected:

![image](https://user-images.githubusercontent.com/34242243/101286923-a0d4a780-37ed-11eb-8246-328f8e2d17df.png)

Am I missing something? Tried deleting both folders to redownload. Same result.

**Comment by derteaser** [comment]
Same here! With the following config just the first font (Montserrat) gets downloaded but including all subsets instead of just latin:
`googleFonts: {
    families: {
      Montserrat: [400, 700],
      Roboto: 400,
      Sanchez: true
    },
    subsets: 'latin',
    display: 'swap',
    download: true
  }`

**Comment by ricardogobbosouza** [comment]
Hi @galaczi, @derteaser 

Google fonts uses your browser based to know which fonts it will download.

This module uses under the hood the [google-fonts-helper](https://github.com/ricardogobbosouza/google-fonts-helper) which defines the default user-agent.
https://github.com/ricardogobbosouza/google-fonts-helper/blob/master/src/index.ts#L104

We need to document the `headers` option in the download area, but you can customize it as you see fit.

**Comment by SkullMasher** [comment]
> We need to document the `headers` option in the download area, but you can customize it as you see fit.

Thanks for the input, how one could modify the headers option to only take latin or other subsets ?

**Comment by retroriff** [comment]
Subsets and wght are not working:

```
googleFonts: {
    display: 'swap',
    download: true,
    families: {
      Roboto:  {
        wght: [300, 700]
      }
    },
    subsets: 'latin'
  },
```

I am getting:

```
@font-face {
                font-family: Roboto;
                font-style: normal;
                font-weight: 400;
                font-display: swap;
                src: url(/_nuxt/fonts/Roboto-400-cyrillic-ext1.493afe7.woff2) format("woff2");
                unicode-range: U+0460-052f, U+1c80-1c88, U+20b4, U+2de0-2dff, U+a640-a69f, U+fe2e-fe2f;
            }
            @font-face {
                font-family: Roboto;
                font-style: normal;
                font-weight: 400;
                font-display: swap;
                src: url(/_nuxt/fonts/Roboto-400-cyrillic2.5e49381.woff2) format("woff2");
                unicode-range: U+0400-045f, U+0490-0491, U+04b0-04b1, U+2116;
            }
            ...
```

**Comment by SwapnilSoni1999** [comment]
Same issue here, Haven't specified any subsets, Still downloading all subsets

**Comment by andrevferreiraa** [comment]
Still happening.

**Comment by ricardogobbosouza** [comment]
Soon I will release the new version of [google-fonts-helper](https://github.com/datalogix/google-fonts-helper) will fix this problem

It is worth remembering that when using `subsets` automatically or the module uses google fonts v1 which does not allow you to define some fonts weights

See https://developers.google.com/fonts/docs/getting_started

**Comment by sh0ber** [comment]
Still happening.
Also, if we can't use `subsets` and get all weights, that seems pretty bad.

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen

**Comment by emirkoni** [comment]
@ricardogobbosouza this issue still occurs, even on the last version, subset + fw doesn't work at all
