### ISSUE TITLE
MIME type is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by lsbyerley** [nuxt-community/google-fonts-module#50]
Anyone seen this error in the network tab when using this module?

`Refused to apply style from 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro&family=display:0,1,2,3,wght@1,s;1,w;1,a;1,p' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

My nuxt config looks like this..

```
buildModules: ['@nuxtjs/google-fonts'],
googleFonts: {
    families: {
      'Source+Sans+Pro': true,
      display: 'swap',
    },
  },
```

**Comment by bart** [comment]
I have exactly the same problem. Reason is the display swap option

**Comment by rafailml** [comment]
```display: 'swap',```
should be outside ```families``` section
```
googleFonts: {
    families: {
      'Source+Sans+Pro': true,
    },
    display: 'swap',
  },
```
