### ISSUE TITLE
Display swap option leads to 400 error: Invalid axisTag

### ISSUE THREAD

**Issue by bart** [nuxt-community/google-fonts-module#60]
When using `display: 'swap'` option it tries to load the font from a URL that responds with a 400 server error.

Example:
```
googleFonts: {
  families: {
    Inter: true,
    display: 'swap',
  },
},
```

Generates `https://fonts.googleapis.com/css2?family=Inter&family=display:0,1,2,3,wght@1,s;1,w;1,a;1,p`

Which results in

```
400: Invalid selector

Invalid axisTag:

display:0,1,2,3,wght@1,s;1,w;1,a;1,p
```

Looks like the generated URL is wrong. Should be `https://fonts.googleapis.com/css2?family=Inter&display=swap` instead.

**Comment by rafailml** [comment]
I thing ```display: 'swap'```, should be outside```families``` section:
```
googleFonts: {
  families: {
    Inter: true,
  },
  display: 'swap',
},
```

**Comment by bart** [comment]
OMG I'm such an idiot. Thanks!!

**Comment by matamune94** [comment]
Hello i can load my font with this option: 
```
  googleFonts: {
    families: {
      Roboto: true
    },
    display: 'swap'
  },
```

Generates https://fonts.googleapis.com/css2?family=Roboto:wght@true&display=swap
