### ISSUE TITLE
Subset and multiple fonts not working

### ISSUE THREAD

**Issue by prathamesh-gharat** [nuxt-community/google-fonts-module#64]
1. https://fonts.googleapis.com/css?family=Lato:wght@400&family=Barlow:wght@500;600&display=swap
2. https://fonts.googleapis.com/css2?family=Lato:wght@400&family=Barlow:wght@500;600&display=swap

Both of the above produce different output. It seems `/css` does not support multiple family parameters.

The first URL (`/css`) is used because I'm using a subset as per the code [[ref](https://github.com/datalogix/google-fonts-helper/blob/master/src/index.ts#L52)].

Example config.
```
  families: {
      Lato: {
        wght: [400],
        ital: [400],
      },
      Barlow: {
        wght: [500, 600],
      },
    },
    display: 'swap',
    preload: true,
    useStylesheet: true,
    subsets: 'latin',
```

**Comment by ricardogobbosouza** [comment]
Soon I will release the new version of [google-fonts-helper](https://github.com/datalogix/google-fonts-helper) will fix this problem

It is worth remembering that when using `subsets` automatically or the module uses google fonts v1 which does not allow you to define some fonts weights

See 
https://developers.google.com/fonts/docs/getting_started
https://developers.google.com/fonts/docs/css2
