### ISSUE TITLE
HTML validation error - Attribute "crossorigin" should omit value

### ISSUE THREAD

**Issue by cwaldvonderlahr** [nuxt-community/google-fonts-module#66]
Hey Nuxt Community,

first thanks for this very nice google fonts module.

In the last days I worked with the Nuxt HTML Validator (https://html-validator.nuxtjs.org/) and I got the error: HTML validation error - Attribute "crossorigin" should omit value. 

Is it possible to change crossorigin="" to crossorigin="anonymous" ?
(Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)

Thanks for short feedback.
Christian

**Comment by ricardogobbosouza** [comment]
Hi @cwaldvonderlahr 
I will fix it soon

**Comment by LucasCtrl** [comment]
Hello,
Any news on this issue ?

**Comment by ricardogobbosouza** [comment]
Hi @LucasCtrl 
Fixed in [v3.0.0-0](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-0)

**Comment by weblabio** [comment]
+1 
I have the same problem with the package `html-to-image`, crossorigin attribute needs to be customized
[](https://github.com/bubkoo/html-to-image/issues/207#issuecomment-1010680144)

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

https://github.com/nuxt-community/google-fonts-module/blob/main/src/module.ts#L134
https://github.com/nuxt-community/google-fonts-module/blob/main/src/module.ts#L206
