### ISSUE TITLE
Can't find type definitions in tarball

### ISSUE THREAD

**Issue by gekkedev** [nuxt-community/google-fonts-module#71]
https://github.com/nuxt-community/google-fonts-module/blob/e08d4aba3c123d65eee8cd1d11cd176bc40d620a/package.json#L11
According to this line, there is a `.d.ts` file to be imported but I cannot find it within the tarball:
```
$ ls ./node_modules/@nuxtjs/google-fonts
CHANGELOG.md  lib  LICENSE  package.json  README.md
```
As you see, there is no type definition file. Wrong directory to be imported from?

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)
