### ISSUE TITLE
Any family '+Sans' is not downloading

### ISSUE THREAD

**Issue by Chlac** [nuxt-community/google-fonts-module#73]
I've even tried the 'Josefin+Sans' from the docs. Completely ignored.
I've tried JosefinSans, Josefin_Sans, 'Josefin+Sans', 'Josefin Sans', Josefin, ... Tried the same for Open Sans.
Nothing works.

Other fonts with a one part name work fine though.

Everything works if not setting "download: true"

**Comment by Andrija84** [comment]
Hi,

Try to remove the fonts.css and fonts folder that was previously created and run build again

**Comment by jonorozcoc** [comment]
Any solution on this?

**Comment by Scaalees** [comment]
Hopefully this helps... The latest package is on v3 which requires Nuxt 3. 

My project is using Nuxt 2, so simply downgrading this package to v2 and it worked perfectly fine.

**Comment by ricardogobbosouza** [comment]
- Use 'Josefin Sans'
- Use the [`overwrite`](https://google-fonts.nuxtjs.org/downloading#overwriting) option 

In next release https://github.com/nuxt-community/google-fonts-module/pull/105  it will be detected automatically

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen
