### ISSUE TITLE
'Noto Sans' fonts can't be downloaded

### ISSUE THREAD

**Issue by Almo98** [nuxt-community/google-fonts-module#74]
The module doesn't download Noto Sans Korean or Japanese font. But there is no problem with any other fonts, I used many. I tried different names for the Noto Sans fonts like 'Noto+Sans+Korean', 'Noto+Sans+Kr', 'Noto+Sans+KR', etc. I also removed the fonts folder and the fonts.css file before every try... Still doesn't work.
P.S. sometimes the module downloads those fonts after all. I guess the problem is that the japanese and korean fonts are broken up into many files.
![font-module](https://user-images.githubusercontent.com/98839151/152033826-0148ee5a-251a-406d-bb69-f40bcc73d392.png)

![font1](https://user-images.githubusercontent.com/98839151/152035247-50110481-b33c-42d3-b72a-45b8a4ec6d17.png)

**Comment by ricardogobbosouza** [comment]
Hi @Almo98 
Soon I will release the new version of [google-fonts-helper](https://github.com/datalogix/google-fonts-helper) will fix this problem

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen
