### ISSUE TITLE
Error 400: Invalid selector

### ISSUE THREAD

**Issue by sabmark** [nuxt-community/google-fonts-module#78]
Packages:
```
"nuxt": "^2.15.7",
"vuetify": "^2.5.5",
"@nuxtjs/google-fonts": "^1.3.0",
```

Config:
````
{
    families: {
        Montserrat: {
            wght: [100, 200, 300],
            ital: [100, 200, 300],
        },
    },
    display: 'swap',
}
````

Resulting Url:
https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,100;1,100;1,200;1,300&display=swap

The problem is that `0,100;` is repeated. I don't know why.

**Comment by ricardogobbosouza** [comment]
Hi @sabmark 
Soon I will release the new version of [google-fonts-helper](https://github.com/datalogix/google-fonts-helper) will fix this problem
