### ISSUE TITLE
v3: 400 Bad Request

### ISSUE THREAD

**Issue by bmulholland** [nuxt-community/google-fonts-module#97]
nuxt 2.15

I upgraded to v3.0.0-0 and ran `yarn dev`. This immediately errors out:

ERROR  400 Bad Request (https://fonts.googleapis.com/css2?family=DM%2BSans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&family=DM%2BSerif%2BText:ital,wght@0,400;1,400&display=swap)

Here's my config from nuxt.config.js:

```
    googleFonts: {
      // Download so there's no external dependencies
      download: true,
      // FYI: if you change any of these fonts, you have to add overwriting: true to allow the plugin
      // to re- download
      overwriting: true,
      families: {
        "DM+Sans": {
          wght: [400, 500, 700],
          ital: [400, 500, 700],
        },
        "DM+Serif+Text": {
          wght: [400],
          ital: [400],
        },
      },
    },
```

**Comment by bmulholland** [comment]
The issue with the URL is that the "+" is URL encoded into %2B; it shouldn't be. The docs still say to include this, however: https://google-fonts.nuxtjs.org/options#families

Changing the + to a space in my config fixes the issue, but this is not documented anywhere.

**Comment by gitinthehole** [comment]
Looked all over for this answer. The flag/note by @bmulholland about it not being documented to use a space instead of a "+" is an issue and impacts both vue 2 and vue 3.

**Comment by ricardogobbosouza** [comment]
In next release https://github.com/nuxt-community/google-fonts-module/pull/105 it will be detected automatically

https://github.com/datalogix/google-fonts-helper/commit/90745d634c7a7d15914fc1f35be2568a00c89455

**Comment by ricardogobbosouza** [comment]
Please try [v3.0.0-1](https://github.com/nuxt-community/google-fonts-module/releases/tag/v3.0.0-1)

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen
